name: Github
on:
    push:
     branches: [github_package ]
  
    pull_request:
     branches: [github_package ]
  
jobs:
   build: 
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
                java-version: '11'
                distribution: 'adopt'
                cache: maven
          
          
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
    - uses: actions/upload-artifact@v1
      with:
            name: Package
            path: staging
